import random
import os
from tkinter import *
from tkinter import ttk

os.system('cls')

class game:
    english_dict = {
        "ambiguous": "open to more than one interpretation; having a double meaning.",
        "cogent": "clear, logical, and convincing.",
        "ephemeral": "lasting for a very short time.",
        "esoteric": "intended for or likely to be understood by only a small number of people with a specialized knowledge or interest.",
        "melancholy": "a deep, persistent sadness or sorrow.",
        "quintessential": "representing the most perfect or typical example of a quality or class.",
        "resilient": "able to withstand or recover quickly from difficult conditions.",
        "serendipity": "the occurrence of events by chance in a happy or beneficial way.",
        "ubiquitous": "present, appearing, or found everywhere.",
        "vex": "to make someone feel annoyed, frustrated, or worried, especially with trivial matters."
    }

    portuguese_dict = {
    "à tarde": "(in the) afternoon",
    "à tarde, à tardinha": "(in the) evening",
    "à volta de": "(a)round (prep)",
    "bicicleta motorizada": "moped",
    "comboio expresso": "express train",
    "cor de laranja": "orange (=colour)",
    "cor de rosa": "pink",
    "de manhã": "(in the) morning",
    "telenovela": "soap opera",
    "a": "at (=time)",
    "a caminho": "on the way",
    "a tempo": "in time",
    "a, para": "to (a place)",
    "abaixo de": "below, under",
    "abelha": "bee",
    "aberto": "open (adj.)",
    "abrir": "to open",
    "absolutamente": "completely, absolutely",
    "acampar": "to camp",
    "aceitar": "to accept",
    "achar": "to find; to have an opinion",
    "aço": "steel",
    "acordar": "to wake up",
    "acordar alguém": "to wake s.o.",
    "ator": "actor",
    "atriz": "actress",
    "açúcar": "sugar",
    "adulto": "adult",
    "advogado": "lawyer",
    "aeroporto": "airport",
    "afiado": "sharp",
    "agência de viagens": "travel agent's",
    "agenda": "diary",
    "diário": "diary",
    "agora": "now",
    "agradável": "pleasant / enjoyable",
    "agradável, bom, simpático": "nice",
    "agradecer": "to thank",
    "agricultor": "farmer",
    "fazendeiro": "farmer",
    "água": "water",
    "água potável": "drinking water",
    "água mineral": "mineral water",
    "aguaceiro": "shower (=weather)",
    "chuvada": "shower (=weather)",
    "chuvarada": "shower (=weather)",
    "aguardar": "to look forward to",
    "aí": "there",
    "ali": "there",
    "ainda": "still (=even now)",
    "ainda não": "not yet",
    "ajudar": "to help",
    "alcatifa": "carpet",
    "tapete": "carpet",
    "carpete": "carpet",
    "álcool": "alcohol",
    "sem álcool": "alcohol (free)",
    "aldeia": "village",
    "vilarejo": "village",
    "povoado": "village",
    "alface": "lettuce",
    "alfândega": "customs (=declare!)",
    "algibeira": "pocket",
    "bolso": "pocket",
    "algodão": "cotton",
    "alguém": "someone, somebody",
    "alho": "garlic",
    "ali": "over there",
    "alimentos": "food (=shopping)",
    "comida": "food (=shopping)",
    "almoço": "lunch, mid-day meal",
    "almofada": "cushion",
    "alojamento": "accommodation",
    "acomodação": "accommodation",
    "alto": "high, tall",
    "altura": "height (of person)",
    "alugar": "to rent, hire",
    "aluno": "pupil",
    "amanhã": "tomorrow",
    "amar": "to love",
    "amarelo": "yellow",
    "amargo": "bitter (taste)",
    "ambos": "both",
    "ambulância": "ambulance",
    "ameixa": "plum",
    "amigo": "friend",
    "amor": "love",
    "ananás": "pineapple",
    "abacaxi": "pineapple",
    "andar": "floor (e.g. 1st floor)",
    "andar de cavalo": "to ride (horse)",
    "andar de cima": "upstairs",
    "andar inferior": "downstairs",
    "andar de baixo": "downstairs",
    "anel": "ring",
    "anfitrião": "host",
    "animal": "animal",
    "animal de estimação": "pet",
    "aniversário": "birthday",
    "ano": "year",
    "ansioso": "anxious",
    "preocupado": "anxious",
    "antes": "before (conj.), beforehand, previously",
    "anteontem": "day before yesterday",
    "antigamente": "formerly, previously",
    "anualmente": "annually",
    "anúncio": "advert",
    "ao lado de": "next to",
    "ao longo de": "along",
    "apanhar sol": "to sunbathe",
    "tomar sol": "to sunbathe",
    "apanhar": "to catch (=bus, etc)",
    "pegar": "to catch (=bus, etc)",
    "aparelhagem": "stereo system",
    "aparelho de som": "stereo system",
    "apartamento": "flat (=accommodation)",
    "apertado": "tight",
    "apetecer": "to feel like (doing s.th)",
    "ter vontade de": "to feel like (doing s.th)",
    "aprender": "to learn",
    "aprendiz": "apprentice",
    "estagiário": "apprentice",
    "aproximadamente": "about, roughly, approximately",
    "aquecer": "to heat",
    "esquentar": "to heat",
    "aquecimento": "heating (central)",
    "calefação": "heating (central)",
    "aqui": "here",
    "ar livre": "open air (in the)",
    "área de serviço": "motorway services",
    "área pedonal": "pedestrian (area)",
    "área para pedestres": "pedestrian (area)",
    "área": "area",
    "distrito": "district",
    "areia": "sand",
    "castelo de areia": "sandcastle",
    "armário": "cupboard",
    "arrumado": "tidy",
    "arrumar": "to tidy up, clear away",
    "arrumar, estacionar": "to park",
    "arte": "art",
    "galeria de arte": "art gallery",
    "artista": "artist",
    "árvore": "tree",
    "árvore de fruta": "fruit tree",
    "às vezes": "sometime(s)",
    "aspirar": "to hoover/ vacuum clean",
    "assar": "to roast",
}

    

    def whatWord(self):
        #englishAmountOfWords = len(self)
        word = random.choice(list(self))
        definition = self.get(word)
        print(word + ': ' + definition)


    def whatLang(self):
        if self == 'english':
            game.whatWord(game.english_dict)
        elif self == 'portuguese':
            game.whatWord(game.portuguese_dict)



language = input("What language you bastard?: ").lower()

game.whatLang(language)